[package]
name = "musl-generator"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]

[dependencies]
lazy_static = "1.0.2"
shared = { path = "../shared" }
libm = { path = ".." }
cortex-m = "0.5.8"
cortex-m-rt = "0.6.5"
cortex-m-semihosting = "0.3.2"
panic-halt = "0.2.0"

